[build.env]
passthrough = [
    "OPENSSL_STATIC",
    "OPENSSL_VENDORED",
]

[target.x86_64-unknown-linux-gnu.env]
OPENSSL_STATIC = "1"
OPENSSL_VENDORED = "1"

[target.aarch64-unknown-linux-gnu.env]
OPENSSL_STATIC = "1"
OPENSSL_VENDORED = "1"

[target.armv7-unknown-linux-gnueabihf.env]
OPENSSL_STATIC = "1"
OPENSSL_VENDORED = "1"
